---
- name: Disable UFW Firewall on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Ensure UFW is installed
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Disable UFW Firewall
      ansible.builtin.command:
        cmd: ufw disable
      register: disable_firewall_result

    - name: Display UFW status after disabling
      ansible.builtin.command:
        cmd: ufw status
      register: ufw_status
      changed_when: false

    - name: Debug - Show UFW status
      ansible.builtin.debug:
        msg: "{{ ufw_status.stdout }}"
