---
- name: Fully Disable UFW Firewall on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Ensure UFW is installed
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Disable UFW Firewall
      ansible.builtin.command:
        cmd: ufw disable
      register: disable_firewall_result

    - name: Stop UFW Service
      ansible.builtin.service:
        name: ufw
        state: stopped

    - name: Disable UFW Service from starting on boot
      ansible.builtin.systemd:
        name: ufw
        enabled: false

    - name: Check UFW Service Status
      ansible.builtin.command:
        cmd: systemctl status ufw
      register: ufw_service_status
      changed_when: false
      failed_when: "'inactive (dead)' not in ufw_service_status.stdout"

    - name: Debug - Show UFW Service Status
      ansible.builtin.debug:
        msg: "{{ ufw_service_status.stdout }}"
