---
- name: Manage UFW Firewall on Ubuntu
  hosts: all
  become: true
  vars:
    firewall_state: "disabled"   # ตั้งค่าเป็น "enabled" เพื่อเปิด Firewall หรือ "disabled" เพื่อปิด

  tasks:
    - name: Ensure UFW is installed
      ansible.builtin.apt:
        name: ufw
        state: present
      when: ansible_os_family == "Debian"

    - name: Disable UFW Firewall
      ansible.builtin.command:
        cmd: ufw disable
      when:
        - firewall_state == "disabled"
        - ansible_os_family == "Debian"

    - name: Enable UFW Firewall
      ansible.builtin.command:
        cmd: ufw enable
      when:
        - firewall_state == "enabled"
        - ansible_os_family == "Debian"
